config/routes.rb
PokerLog::Application.routes.draw do
  root to: 'games#index'
  resources :users
  resources :games
  match 'charts' => 'charts#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :earned, :end_time, :notes, :start_date, :start_time, :game_type
  belongs_to :user

  GameTypes = ['NLHE', 'LHE', 'PLO', 'Limit Omaha 8/b', 'Stud Hi', 'Stud 8/b', 'Razz']

  default_scope order: 'games.start_date DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :games, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery

  before_filter :authorize

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    @games = current_user.games.sort_by(&:start_date)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = current_user.games.sort_by(&:start_date)
    @game = Game.new
  end

  def show
  end

  def new
    @game = Game.new
  end
  
  def create
    @game = Game.new(params[:game])
    @game.user_id = current_user.id
    @game.time_played = ((@game.end_time - @game.start_time) / 3600 )
    @game.save
    redirect_to games_url, notice: "Saved!"
  end

  def edit
  end

  def update
  end

  def destroy
    Game.find(params[:id]).destroy 
    redirect_to games_path, notice: "Deleted Game"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  unloadable

  skip_before_filter :authorize,   :only => [:new, :create]
  before_filter :redirect_to_root, :only => [:new, :create], :if => :signed_in?

  def new
    @user = user_from_params
    render :template => 'users/new'
  end

  def create
    @user = user_from_params
    if @user.save
      sign_in(@user)
      redirect_back_or(url_after_create)
    else
      flash_failure_after_create
      render :template => 'users/new'
    end
  end

  private

  def flash_failure_after_create
    flash.now[:notice] = translate(:bad_email_or_password,
      :scope   => [:clearance, :controllers, :passwords],
      :default => "Must be a valid email address. Password can't be blank.")
  end

  def url_after_create
    '/'
  end

  def user_from_params
    user_params = params[:user] || Hash.new
    email, password = user_params.delete(:email), user_params.delete(:password)
    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/charts/index.html.erb
<div id="games_chart" style"width: 560px; height: 300px;"></div>
<%= javascript_include_tag "application", "highcharts" %>
<table class="pretty">
<script type="text/javascript" charset="utf-8">
  $(function () {
  new Highcharts.Chart({
    chart: { renderTo: 'games_chart' },
    title: { text: 'Games by Day' },
    xAxis: { type: 'datetime' },
    yAxis: {
      title: { text: 'Dollars'}
    },
    series: [{ 
    name: "Earnings",
    pointInterval: <%= 1.day * 1000 %>,
    pointStart: <%= 2.weeks.ago.at_midnight.to_i * 1000  %>, 
    data: [ <%= @games.map(&:earned).join(', ') %>]
      }]
});
})
</script>
</table>

app/views/games/graphs.html.erb
<div id="games_chart" style"width: 560px; height: 300px;"></div>
<%= javascript_include_tag "application", "highcharts" %>
<table class="pretty">
<script type="text/javascript" charset="utf-8">
  $(function () {
  new Highcharts.Chart({
    chart: { renderTo: 'games_chart' },
    title: { text: 'Games by Day' },
    xAxis: { type: 'datetime' },
    yAxis: {
      title: { text: 'Dollars'}
    },
    series: [{
        <% @games.each do |game| %>
        {
          data: <%= game.earned %>
        },
        <% end %>
      }];
});
</script>
</table>

app/views/games/index.html.erb
<html>
<body>
<%- model_class = Game.new.class -%>
<table class="table table-striepd">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:start_time) %></th>
      <th><%= model_class.human_attribute_name(:end_time) %></th>
      <th><%= model_class.human_attribute_name(:time_played) %></th>
      <th><%= model_class.human_attribute_name(:game_type) %></th>
      <th><%= model_class.human_attribute_name(:earned) %></th>
      <th><%= model_class.human_attribute_name(:notes) %></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.start_date.strftime('%B %e, %Y') %></td>
        <td><%= game.start_time.strftime('%I:%M %p') %></td>
        <td><%= game.end_time.strftime('%I:%M %p') %></td>
        <td><%= game.time_played %></td>
        <td><%= game.game_type %></td>
        <td><%= number_to_currency(game.earned) %></td>
        <td><%= game.notes %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_game_path(game), :class => 'btn btn-mini' %>
          <%= link_to 'Delete', game_path(game), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><b>Total Sessions:</b> <%= current_user.games.count(:all) %></p>
<p><b>Total Time Played:</b> <%= current_user.games.sum(:time_played) %> hours</p>
<p><b>Total Earned:</b> <%= number_to_currency(current_user.games.sum(:earned)) %></p>
<% if current_user.games.sum(:time_played) < 1 %>
  <p><b>Hourly Rate:</b> N/A </p>
<% else %>
  <p><b>Hourly Rate:</b> <%= number_to_currency((current_user.games.sum(:earned) / current_user.games.sum(:time_played))) %> per hour</p>
<% end %>

<%= link_to t('.new', :default => t("helpers.links.new")),
    new_game_path,
    :class => 'btn btn-primary' %>
</body>
</html>

app/views/games/new.html.erb
<html>
<body>
<%= form_for(@game) do |form| %>
  <p>Start Date: <%= form.hidden_field :start_date %><%= text_field_tag :start_date_display %>
  <p>Start Time: <%= form.text_field :start_time %>
  <p>End Time: <%= form.text_field :end_time %>
  <p>Earnings: <%= form.text_field :earned %>
  <p>Game Type: <%= select(:game, :game_type, Game::GameTypes) %>
  <p>Notes: <%= form.text_field :notes %>
  <p><%= form.submit "Submit" %></div>
<% end %>
</body>
</html>

app/views/layouts/_ga.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33394858-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PokerLog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href=<% root_path %>>ThePokerLog</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "List of Games", root_path  %></li>
              <li><%= link_to "New Entry", new_game_path  %></li>
              <li><%= link_to "Graphs", "/charts"  %></li>
              <% if signed_in? %><li><a>Welcome, <%= current_user.email %>!</a></li><li> <%= link_to "Sign Out", sign_out_path, :method => :delete %></li><% else %><li><%= link_to "Sign In", sign_in_path %></li><% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>News</h3>
                <ul class="nav nav-list">
                  <li><%= link_to "Click to make the maneys", "#"  %></li>
                  <li><%= link_to "Recent Additions", "#"  %></li>
                  <li><%= link_to "Future Additions", "#"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Rolled Aces 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application", "highcharts" %>
    <%= render 'layouts/ga' if Rails.env.production? %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text_field">
  <%= form.label :email %>
  <%= form.text_field :email, :type => "email" %>
</div>
<div class="password_field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for @user do |form| %>
  <%= render :partial => '/users/form', :object => form %>
  <%= form.submit 'Sign up' %>
<% end %>